//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Star_SecurityEntities : DbContext
    {
        public db_Star_SecurityEntities()
            : base("name=db_Star_SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_branches> tb_branches { get; set; }
        public virtual DbSet<tb_Client_Sub_Services> tb_Client_Sub_Services { get; set; }
        public virtual DbSet<tb_Services> tb_Services { get; set; }
        public virtual DbSet<tb_Sub_Services> tb_Sub_Services { get; set; }
        public virtual DbSet<tb_Users> tb_Users { get; set; }
        public virtual DbSet<tb_Vacancies> tb_Vacancies { get; set; }
    }
}
