//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_branches
    {
        public int branch_id { get; set; }
        public string address { get; set; }
        public string contact_details { get; set; }
        public int contact_person { get; set; }
        public int admin_id { get; set; }
    
        public virtual tb_Users tb_Users { get; set; }
    }
}
