//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Client_Sub_Services
    {
        public int client_sub_service_id { get; set; }
        public int sub_service_id { get; set; }
        public int client_id { get; set; }
        public int staff_id_emp { get; set; }
    
        public virtual tb_Users tb_Users { get; set; }
        public virtual tb_Users tb_Users1 { get; set; }
        public virtual tb_Sub_Services tb_Sub_Services { get; set; }
    }
}
