//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_Users
    {
        internal object email_address;
        internal DateTime join_date;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Users()
        {
            this.tb_branches = new HashSet<tb_branches>();
            this.tb_Client_Sub_Services = new HashSet<tb_Client_Sub_Services>();
            this.tb_Client_Sub_Services1 = new HashSet<tb_Client_Sub_Services>();
            this.tb_Services = new HashSet<tb_Services>();
            this.tb_Sub_Services = new HashSet<tb_Sub_Services>();
            this.tb_Users1 = new HashSet<tb_Users>();
            this.tb_Vacancies = new HashSet<tb_Vacancies>();
        }
    
        public int user_id { get; set; }

        [Required(ErrorMessage = "Please enter employee code.")]
        [Range(1000, 99999, ErrorMessage = "Employee Code must be 4 or 5 digit long.")]
        public int emp_code { get; set; }

        [Required(ErrorMessage = "Please enter your name.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Name cannot be longer than 100 characters")]

        public string name { get; set; }

        [Required(ErrorMessage = "Please enter contact number.")]
        [StringLength(15, MinimumLength = 1, ErrorMessage = "Contact number cannot be longer than 15 characters")]
        [RegularExpression(@"[0][3][0-9]{2}[\-]?[0-9]{7}", ErrorMessage = "Correct format is: 0333(-)3333333.")]

        public string contact_num { get; set; }
        public string qualification { get; set; }
        public string department { get; set; }

        [Required(ErrorMessage = "Please enter email address.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Email address must be at least 5 characters long and cannot be longer than 50 characters")]
        public string email { get; set; }

        [Required(ErrorMessage = "Please enter password.")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "password cannot be longer than 20 characters")]
        public string password { get; set; }

        [Required(ErrorMessage = "Please enter your address.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Address cannot be longer than 50 characters")]
        public string address { get; set; }

        [Required(ErrorMessage = "Please enter your role.")]
        public string role { get; set; }
        public string grade { get; set; }
        public string client { get; set; }
        public string achievements { get; set; }
        public string services_availed { get; set; }
        public int admin_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_branches> tb_branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Client_Sub_Services> tb_Client_Sub_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Client_Sub_Services> tb_Client_Sub_Services1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Services> tb_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Sub_Services> tb_Sub_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Users> tb_Users1 { get; set; }
        public virtual tb_Users tb_Users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Vacancies> tb_Vacancies { get; set; }
        public DateTime updated_at { get; internal set; }
        public bool verified_user { get; internal set; }
    }
}
